title: cramja's golbja
email: marc.spehlmann@gmail.com
description: marc's blog. I write about my work, research, and ideas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spehl.net"
github_username:  cramja

# Build settings
markdown: kramdown
plugins: 
  - jekyll-paginate
  - jekyll/scholar

paginate: 5

scholar:
  style: acm-sig-proceedings
  source: _citations

exclude:
  - Gemfile
  - Gemfile.lock
